### ISSUE TITLE
偏好设置复选框和文字之间有对齐问题

### ISSUE THREAD

**Issue by stricklandye** [AntonVanke/typora-Aspartate-theme#1]
![微信图片_20211129113320](https://user-images.githubusercontent.com/24771975/143804685-ce5c9197-d8fe-4a99-afaa-d1e493ba9788.png)

而且感觉复选框和文字之间太过紧凑了

**Comment by AntonVanke** [comment]
谢谢提醒，这个问题确实存在。
在浏览器中的复选框是正常的，但到程序里就乱了

**Comment by stricklandye** [comment]
用了几天，我还是比较喜欢这个主题的，高亮啊代码块都比较喜欢。
目前来说还发现一个小问题就是，搜索框那边好像对齐也有些问题。
我不是特别会前端，不知道作者是否有精力稍微优化下呢

**Comment by AntonVanke** [comment]
> 用了几天，我还是比较喜欢这个主题的，高亮啊代码块都比较喜欢。 目前来说还发现一个小问题就是，搜索框那边好像对齐也有些问题。 我不是特别会前端，不知道作者是否有精力稍微优化下呢

会的，不过这几天我在准备四级考试😄

**Comment by FrozenArcher** [comment]
你好，我现在使用0.18的版本，还是有这个问题。
![2023-02-04_00-54](https://user-images.githubusercontent.com/61831273/216661504-5a22e849-5c10-4314-9b4f-3a65fc779dbf.png)
